version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-db
    networks:
      - enet

    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build:
      dockerfile: Dockerfile
    image: product-service
    networks:
      - enet
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  db:
    driver: local
networks:
  enet:
    driver: bridge


